version: '3'

services:
    wedding-server:
        container_name: wedding-server
        build: ./
        ports:
          - 4000:4000
        restart: unless-stopped
        env_file:
          - ./.env-docker
